#server:
#  port: 8081
#spring:
#  batch:
#    jdbc:
#      initialize-schema: always
#  jpa:
#    hibernate:
#      ddl-auto: none
#    show-sql: true
#    database-platform: org.hibernate.dialect.H2Dialect
#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:dataSource1;DB_CLOSE_DELAY=-1
#    username: sa
#    password:
#    driverClassName: org.h2.Driver
#    initialization-mode: always
#  seconddatasource:
#    url: jdbc:h2:mem:dataSource2;DB_CLOSE_DELAY=-1
#    username: sa
#    password:
#    driverClassName: org.h2.Driver
#    initialization-mode: always
#
